//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Datos.WS_PIA {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="API_MostrarServicioPIASoap", Namespace="http://tempuri.org/")]
    public partial class API_MostrarServicioPIA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MostrarServicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostrarPagoPIAsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarEstadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public API_MostrarServicioPIA() {
            this.Url = global::Datos.Properties.Settings.Default.Datos_WS_PIA_API_MostrarServicioPIA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MostrarServicioCompletedEventHandler MostrarServicioCompleted;
        
        /// <remarks/>
        public event MostrarPagoPIAsCompletedEventHandler MostrarPagoPIAsCompleted;
        
        /// <remarks/>
        public event ActualizarEstadoCompletedEventHandler ActualizarEstadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostrarServicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servicio MostrarServicio() {
            object[] results = this.Invoke("MostrarServicio", new object[0]);
            return ((Servicio)(results[0]));
        }
        
        /// <remarks/>
        public void MostrarServicioAsync() {
            this.MostrarServicioAsync(null);
        }
        
        /// <remarks/>
        public void MostrarServicioAsync(object userState) {
            if ((this.MostrarServicioOperationCompleted == null)) {
                this.MostrarServicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarServicioOperationCompleted);
            }
            this.InvokeAsync("MostrarServicio", new object[0], this.MostrarServicioOperationCompleted, userState);
        }
        
        private void OnMostrarServicioOperationCompleted(object arg) {
            if ((this.MostrarServicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarServicioCompleted(this, new MostrarServicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostrarPagoPIAs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MostrarPagoPIA[] MostrarPagoPIAs(string cedula) {
            object[] results = this.Invoke("MostrarPagoPIAs", new object[] {
                        cedula});
            return ((MostrarPagoPIA[])(results[0]));
        }
        
        /// <remarks/>
        public void MostrarPagoPIAsAsync(string cedula) {
            this.MostrarPagoPIAsAsync(cedula, null);
        }
        
        /// <remarks/>
        public void MostrarPagoPIAsAsync(string cedula, object userState) {
            if ((this.MostrarPagoPIAsOperationCompleted == null)) {
                this.MostrarPagoPIAsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarPagoPIAsOperationCompleted);
            }
            this.InvokeAsync("MostrarPagoPIAs", new object[] {
                        cedula}, this.MostrarPagoPIAsOperationCompleted, userState);
        }
        
        private void OnMostrarPagoPIAsOperationCompleted(object arg) {
            if ((this.MostrarPagoPIAsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarPagoPIAsCompleted(this, new MostrarPagoPIAsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarEstado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarEstado(string cod_pago) {
            object[] results = this.Invoke("ActualizarEstado", new object[] {
                        cod_pago});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarEstadoAsync(string cod_pago) {
            this.ActualizarEstadoAsync(cod_pago, null);
        }
        
        /// <remarks/>
        public void ActualizarEstadoAsync(string cod_pago, object userState) {
            if ((this.ActualizarEstadoOperationCompleted == null)) {
                this.ActualizarEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarEstadoOperationCompleted);
            }
            this.InvokeAsync("ActualizarEstado", new object[] {
                        cod_pago}, this.ActualizarEstadoOperationCompleted, userState);
        }
        
        private void OnActualizarEstadoOperationCompleted(object arg) {
            if ((this.ActualizarEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarEstadoCompleted(this, new ActualizarEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servicio {
        
        private string nombreField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarPagoPIA {
        
        private string cedulaField;
        
        private string cod_pagoField;
        
        private decimal montoField;
        
        private string estadoField;
        
        private string nServicioField;
        
        /// <remarks/>
        public string cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        public string cod_pago {
            get {
                return this.cod_pagoField;
            }
            set {
                this.cod_pagoField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string nServicio {
            get {
                return this.nServicioField;
            }
            set {
                this.nServicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MostrarServicioCompletedEventHandler(object sender, MostrarServicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servicio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servicio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MostrarPagoPIAsCompletedEventHandler(object sender, MostrarPagoPIAsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarPagoPIAsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarPagoPIAsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MostrarPagoPIA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MostrarPagoPIA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarEstadoCompletedEventHandler(object sender, ActualizarEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591