//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Datos.WS_MQULst {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="APIMQU_ADSoap", Namespace="http://tempuri.org/")]
    public partial class APIMQU_AD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActualizarDatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarDatoscodpagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarDatoscodpagocondtpagoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public APIMQU_AD() {
            this.Url = global::Datos.Properties.Settings.Default.Datos_WS_MQULst_APIMQU_AD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActualizarDatosCompletedEventHandler ActualizarDatosCompleted;
        
        /// <remarks/>
        public event ActualizarDatoscodpagoCompletedEventHandler ActualizarDatoscodpagoCompleted;
        
        /// <remarks/>
        public event ActualizarDatoscodpagocondtpagoCompletedEventHandler ActualizarDatoscodpagocondtpagoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarDatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarDatos(string cedula, string codpago) {
            this.Invoke("ActualizarDatos", new object[] {
                        cedula,
                        codpago});
        }
        
        /// <remarks/>
        public void ActualizarDatosAsync(string cedula, string codpago) {
            this.ActualizarDatosAsync(cedula, codpago, null);
        }
        
        /// <remarks/>
        public void ActualizarDatosAsync(string cedula, string codpago, object userState) {
            if ((this.ActualizarDatosOperationCompleted == null)) {
                this.ActualizarDatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDatosOperationCompleted);
            }
            this.InvokeAsync("ActualizarDatos", new object[] {
                        cedula,
                        codpago}, this.ActualizarDatosOperationCompleted, userState);
        }
        
        private void OnActualizarDatosOperationCompleted(object arg) {
            if ((this.ActualizarDatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDatosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarDatoscodpago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarDatoscodpago(string codpago) {
            this.Invoke("ActualizarDatoscodpago", new object[] {
                        codpago});
        }
        
        /// <remarks/>
        public void ActualizarDatoscodpagoAsync(string codpago) {
            this.ActualizarDatoscodpagoAsync(codpago, null);
        }
        
        /// <remarks/>
        public void ActualizarDatoscodpagoAsync(string codpago, object userState) {
            if ((this.ActualizarDatoscodpagoOperationCompleted == null)) {
                this.ActualizarDatoscodpagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDatoscodpagoOperationCompleted);
            }
            this.InvokeAsync("ActualizarDatoscodpago", new object[] {
                        codpago}, this.ActualizarDatoscodpagoOperationCompleted, userState);
        }
        
        private void OnActualizarDatoscodpagoOperationCompleted(object arg) {
            if ((this.ActualizarDatoscodpagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDatoscodpagoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarDatoscodpagocondtpago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarDatoscodpagocondtpago(string codpago) {
            this.Invoke("ActualizarDatoscodpagocondtpago", new object[] {
                        codpago});
        }
        
        /// <remarks/>
        public void ActualizarDatoscodpagocondtpagoAsync(string codpago) {
            this.ActualizarDatoscodpagocondtpagoAsync(codpago, null);
        }
        
        /// <remarks/>
        public void ActualizarDatoscodpagocondtpagoAsync(string codpago, object userState) {
            if ((this.ActualizarDatoscodpagocondtpagoOperationCompleted == null)) {
                this.ActualizarDatoscodpagocondtpagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDatoscodpagocondtpagoOperationCompleted);
            }
            this.InvokeAsync("ActualizarDatoscodpagocondtpago", new object[] {
                        codpago}, this.ActualizarDatoscodpagocondtpagoOperationCompleted, userState);
        }
        
        private void OnActualizarDatoscodpagocondtpagoOperationCompleted(object arg) {
            if ((this.ActualizarDatoscodpagocondtpagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDatoscodpagocondtpagoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarDatosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarDatoscodpagoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarDatoscodpagocondtpagoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591