//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5022/API_MostrarServicioPCA.asmx")]
        public string Datos_WS_PCA_API_MostrarServicioPCA {
            get {
                return ((string)(this["Datos_WS_PCA_API_MostrarServicioPCA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5014/API_MostrarServicioPIT.asmx")]
        public string Datos_WS_PIT_API_MostrarServicioPIT {
            get {
                return ((string)(this["Datos_WS_PIT_API_MostrarServicioPIT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5019/API_MostrarServicioPAN.asmx")]
        public string Datos_WS_PAN_API_MostrarServicioPAN {
            get {
                return ((string)(this["Datos_WS_PAN_API_MostrarServicioPAN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5005/API_MostrarServicioPTO.asmx")]
        public string Datos_WS_PTO_API_MostrarServicioPTO {
            get {
                return ((string)(this["Datos_WS_PTO_API_MostrarServicioPTO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5020/API_MostrarPagoPDT.asmx")]
        public string Datos_WS_PDT_API_MostrarPagoPDT {
            get {
                return ((string)(this["Datos_WS_PDT_API_MostrarPagoPDT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5015/API_MostrarServicioPAL.asmx")]
        public string Datos_WS_PAL_API_MostrarServicioPAL {
            get {
                return ((string)(this["Datos_WS_PAL_API_MostrarServicioPAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5016/API_MostrarServicioPMX.asmx")]
        public string Datos_WS_PMX_API_MostrarServicioPMX {
            get {
                return ((string)(this["Datos_WS_PMX_API_MostrarServicioPMX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5011/Api_Integracion.asmx")]
        public string Datos_WS_PRJ_Api_Integracion {
            get {
                return ((string)(this["Datos_WS_PRJ_Api_Integracion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5013/API_MostrarServicioPSM.asmx")]
        public string Datos_WS_PSM_API_MostrarServicioPSM {
            get {
                return ((string)(this["Datos_WS_PSM_API_MostrarServicioPSM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.0.58:5012/API_MostrarServicioPMA.asmx")]
        public string Datos_WS_PMA_API_MostrarServicioPMA {
            get {
                return ((string)(this["Datos_WS_PMA_API_MostrarServicioPMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.7.7:5050/APIMQU_MS.asmx")]
        public string Datos_WS_MQUServ_APIMQU_MS {
            get {
                return ((string)(this["Datos_WS_MQUServ_APIMQU_MS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.7.7:5052/APIMQU_AD.asmx")]
        public string Datos_WS_MQULst_APIMQU_AD {
            get {
                return ((string)(this["Datos_WS_MQULst_APIMQU_AD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.7.7:5051/APIMQU_MD.asmx")]
        public string Datos_WS_MQUlLstPagos_APIMQU_MD {
            get {
                return ((string)(this["Datos_WS_MQUlLstPagos_APIMQU_MD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.7.7:5051/API_MDP.asmx")]
        public string Datos_WS_MQUPGA_API_MDP {
            get {
                return ((string)(this["Datos_WS_MQUPGA_API_MDP"]));
            }
        }
    }
}
