//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Datos.WS_PAL {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="API_MostrarServicioPALSoap", Namespace="http://tempuri.org/")]
    public partial class API_MostrarServicioPAL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mostrarServicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostrarPagosPALOperationCompleted;
        
        private System.Threading.SendOrPostCallback mostrarPagosPALsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarEstadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public API_MostrarServicioPAL() {
            this.Url = global::Datos.Properties.Settings.Default.Datos_WS_PAL_API_MostrarServicioPAL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mostrarServicioCompletedEventHandler mostrarServicioCompleted;
        
        /// <remarks/>
        public event MostrarPagosPALCompletedEventHandler MostrarPagosPALCompleted;
        
        /// <remarks/>
        public event mostrarPagosPALsCompletedEventHandler mostrarPagosPALsCompleted;
        
        /// <remarks/>
        public event ActualizarEstadoCompletedEventHandler ActualizarEstadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mostrarServicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servicio mostrarServicio() {
            object[] results = this.Invoke("mostrarServicio", new object[0]);
            return ((Servicio)(results[0]));
        }
        
        /// <remarks/>
        public void mostrarServicioAsync() {
            this.mostrarServicioAsync(null);
        }
        
        /// <remarks/>
        public void mostrarServicioAsync(object userState) {
            if ((this.mostrarServicioOperationCompleted == null)) {
                this.mostrarServicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmostrarServicioOperationCompleted);
            }
            this.InvokeAsync("mostrarServicio", new object[0], this.mostrarServicioOperationCompleted, userState);
        }
        
        private void OnmostrarServicioOperationCompleted(object arg) {
            if ((this.mostrarServicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mostrarServicioCompleted(this, new mostrarServicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MostrarPagosPAL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MostrarPagosPAL MostrarPagosPAL(PAGO pago) {
            object[] results = this.Invoke("MostrarPagosPAL", new object[] {
                        pago});
            return ((MostrarPagosPAL)(results[0]));
        }
        
        /// <remarks/>
        public void MostrarPagosPALAsync(PAGO pago) {
            this.MostrarPagosPALAsync(pago, null);
        }
        
        /// <remarks/>
        public void MostrarPagosPALAsync(PAGO pago, object userState) {
            if ((this.MostrarPagosPALOperationCompleted == null)) {
                this.MostrarPagosPALOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostrarPagosPALOperationCompleted);
            }
            this.InvokeAsync("MostrarPagosPAL", new object[] {
                        pago}, this.MostrarPagosPALOperationCompleted, userState);
        }
        
        private void OnMostrarPagosPALOperationCompleted(object arg) {
            if ((this.MostrarPagosPALCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostrarPagosPALCompleted(this, new MostrarPagosPALCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mostrarPagosPALs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MostrarPagosPAL[] mostrarPagosPALs(string cedula) {
            object[] results = this.Invoke("mostrarPagosPALs", new object[] {
                        cedula});
            return ((MostrarPagosPAL[])(results[0]));
        }
        
        /// <remarks/>
        public void mostrarPagosPALsAsync(string cedula) {
            this.mostrarPagosPALsAsync(cedula, null);
        }
        
        /// <remarks/>
        public void mostrarPagosPALsAsync(string cedula, object userState) {
            if ((this.mostrarPagosPALsOperationCompleted == null)) {
                this.mostrarPagosPALsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmostrarPagosPALsOperationCompleted);
            }
            this.InvokeAsync("mostrarPagosPALs", new object[] {
                        cedula}, this.mostrarPagosPALsOperationCompleted, userState);
        }
        
        private void OnmostrarPagosPALsOperationCompleted(object arg) {
            if ((this.mostrarPagosPALsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mostrarPagosPALsCompleted(this, new mostrarPagosPALsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarEstado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarEstado(string cod_pago) {
            object[] results = this.Invoke("ActualizarEstado", new object[] {
                        cod_pago});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarEstadoAsync(string cod_pago) {
            this.ActualizarEstadoAsync(cod_pago, null);
        }
        
        /// <remarks/>
        public void ActualizarEstadoAsync(string cod_pago, object userState) {
            if ((this.ActualizarEstadoOperationCompleted == null)) {
                this.ActualizarEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarEstadoOperationCompleted);
            }
            this.InvokeAsync("ActualizarEstado", new object[] {
                        cod_pago}, this.ActualizarEstadoOperationCompleted, userState);
        }
        
        private void OnActualizarEstadoOperationCompleted(object arg) {
            if ((this.ActualizarEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarEstadoCompleted(this, new ActualizarEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servicio {
        
        private string nombreField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarPagosPAL {
        
        private string cedulaField;
        
        private string cod_pagoField;
        
        private decimal montoField;
        
        private string estadoField;
        
        private string nServicioField;
        
        /// <remarks/>
        public string cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        public string cod_pago {
            get {
                return this.cod_pagoField;
            }
            set {
                this.cod_pagoField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string nServicio {
            get {
                return this.nServicioField;
            }
            set {
                this.nServicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TIPOPLAN {
        
        private SUSCRIPCION[] sUSCRIPCIONField;
        
        private int tIPOPLAN_IDField;
        
        private string tIPOPLAN_NOMBREField;
        
        private string tIPOPLAN_DURACIONField;
        
        private System.Nullable<decimal> tIPOPLAN_PRECIOField;
        
        private System.Nullable<bool> tIPOPLAN_ESTADOField;
        
        /// <remarks/>
        public SUSCRIPCION[] SUSCRIPCION {
            get {
                return this.sUSCRIPCIONField;
            }
            set {
                this.sUSCRIPCIONField = value;
            }
        }
        
        /// <remarks/>
        public int TIPOPLAN_ID {
            get {
                return this.tIPOPLAN_IDField;
            }
            set {
                this.tIPOPLAN_IDField = value;
            }
        }
        
        /// <remarks/>
        public string TIPOPLAN_NOMBRE {
            get {
                return this.tIPOPLAN_NOMBREField;
            }
            set {
                this.tIPOPLAN_NOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string TIPOPLAN_DURACION {
            get {
                return this.tIPOPLAN_DURACIONField;
            }
            set {
                this.tIPOPLAN_DURACIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TIPOPLAN_PRECIO {
            get {
                return this.tIPOPLAN_PRECIOField;
            }
            set {
                this.tIPOPLAN_PRECIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> TIPOPLAN_ESTADO {
            get {
                return this.tIPOPLAN_ESTADOField;
            }
            set {
                this.tIPOPLAN_ESTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SUSCRIPCION {
        
        private CLIENTE cLIENTEField;
        
        private TIPOPLAN tIPOPLANField;
        
        private int sUS_IDField;
        
        private string cLI_IDField;
        
        private int tIPOPLAN_IDField;
        
        private System.Nullable<System.DateTime> sUS_STARTDATEField;
        
        private System.Nullable<System.DateTime> sUS_ENDDATEField;
        
        private System.Nullable<bool> sUS_RENOVACIONAUTOField;
        
        private System.Nullable<bool> sUS_ESTADOField;
        
        /// <remarks/>
        public CLIENTE CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public TIPOPLAN TIPOPLAN {
            get {
                return this.tIPOPLANField;
            }
            set {
                this.tIPOPLANField = value;
            }
        }
        
        /// <remarks/>
        public int SUS_ID {
            get {
                return this.sUS_IDField;
            }
            set {
                this.sUS_IDField = value;
            }
        }
        
        /// <remarks/>
        public string CLI_ID {
            get {
                return this.cLI_IDField;
            }
            set {
                this.cLI_IDField = value;
            }
        }
        
        /// <remarks/>
        public int TIPOPLAN_ID {
            get {
                return this.tIPOPLAN_IDField;
            }
            set {
                this.tIPOPLAN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SUS_STARTDATE {
            get {
                return this.sUS_STARTDATEField;
            }
            set {
                this.sUS_STARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SUS_ENDDATE {
            get {
                return this.sUS_ENDDATEField;
            }
            set {
                this.sUS_ENDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> SUS_RENOVACIONAUTO {
            get {
                return this.sUS_RENOVACIONAUTOField;
            }
            set {
                this.sUS_RENOVACIONAUTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> SUS_ESTADO {
            get {
                return this.sUS_ESTADOField;
            }
            set {
                this.sUS_ESTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CLIENTE {
        
        private ESCUCHAS[] eSCUCHASField;
        
        private PAGO[] pAGOField;
        
        private SUSCRIPCION[] sUSCRIPCIONField;
        
        private string cLI_IDField;
        
        private string cLI_NOMBREField;
        
        private string cLI_APELLIDOField;
        
        private string cLI_PAISField;
        
        private string cLI_EMAILField;
        
        private System.Nullable<bool> cLI_ESTADOField;
        
        /// <remarks/>
        public ESCUCHAS[] ESCUCHAS {
            get {
                return this.eSCUCHASField;
            }
            set {
                this.eSCUCHASField = value;
            }
        }
        
        /// <remarks/>
        public PAGO[] PAGO {
            get {
                return this.pAGOField;
            }
            set {
                this.pAGOField = value;
            }
        }
        
        /// <remarks/>
        public SUSCRIPCION[] SUSCRIPCION {
            get {
                return this.sUSCRIPCIONField;
            }
            set {
                this.sUSCRIPCIONField = value;
            }
        }
        
        /// <remarks/>
        public string CLI_ID {
            get {
                return this.cLI_IDField;
            }
            set {
                this.cLI_IDField = value;
            }
        }
        
        /// <remarks/>
        public string CLI_NOMBRE {
            get {
                return this.cLI_NOMBREField;
            }
            set {
                this.cLI_NOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string CLI_APELLIDO {
            get {
                return this.cLI_APELLIDOField;
            }
            set {
                this.cLI_APELLIDOField = value;
            }
        }
        
        /// <remarks/>
        public string CLI_PAIS {
            get {
                return this.cLI_PAISField;
            }
            set {
                this.cLI_PAISField = value;
            }
        }
        
        /// <remarks/>
        public string CLI_EMAIL {
            get {
                return this.cLI_EMAILField;
            }
            set {
                this.cLI_EMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CLI_ESTADO {
            get {
                return this.cLI_ESTADOField;
            }
            set {
                this.cLI_ESTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ESCUCHAS {
        
        private AUDIOS aUDIOSField;
        
        private CLIENTE cLIENTEField;
        
        private int eSCUCHA_IDField;
        
        private int aUDIO_IDField;
        
        private string cLI_IDField;
        
        private System.Nullable<System.DateTime> eSCUCHA_FECHAField;
        
        private bool eSCHUCHA_ESTADOField;
        
        /// <remarks/>
        public AUDIOS AUDIOS {
            get {
                return this.aUDIOSField;
            }
            set {
                this.aUDIOSField = value;
            }
        }
        
        /// <remarks/>
        public CLIENTE CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public int ESCUCHA_ID {
            get {
                return this.eSCUCHA_IDField;
            }
            set {
                this.eSCUCHA_IDField = value;
            }
        }
        
        /// <remarks/>
        public int AUDIO_ID {
            get {
                return this.aUDIO_IDField;
            }
            set {
                this.aUDIO_IDField = value;
            }
        }
        
        /// <remarks/>
        public string CLI_ID {
            get {
                return this.cLI_IDField;
            }
            set {
                this.cLI_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ESCUCHA_FECHA {
            get {
                return this.eSCUCHA_FECHAField;
            }
            set {
                this.eSCUCHA_FECHAField = value;
            }
        }
        
        /// <remarks/>
        public bool ESCHUCHA_ESTADO {
            get {
                return this.eSCHUCHA_ESTADOField;
            }
            set {
                this.eSCHUCHA_ESTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AUDIOS {
        
        private int aUDIO_IDField;
        
        private string aUDIO_TITULOField;
        
        private string aUDIO_DURACIONField;
        
        private string aUDIO_AUTORField;
        
        private System.Nullable<System.DateTime> aUDIO_FECHAField;
        
        private bool aUDIO_ESTADOField;
        
        private ESCUCHAS[] eSCUCHASField;
        
        /// <remarks/>
        public int AUDIO_ID {
            get {
                return this.aUDIO_IDField;
            }
            set {
                this.aUDIO_IDField = value;
            }
        }
        
        /// <remarks/>
        public string AUDIO_TITULO {
            get {
                return this.aUDIO_TITULOField;
            }
            set {
                this.aUDIO_TITULOField = value;
            }
        }
        
        /// <remarks/>
        public string AUDIO_DURACION {
            get {
                return this.aUDIO_DURACIONField;
            }
            set {
                this.aUDIO_DURACIONField = value;
            }
        }
        
        /// <remarks/>
        public string AUDIO_AUTOR {
            get {
                return this.aUDIO_AUTORField;
            }
            set {
                this.aUDIO_AUTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AUDIO_FECHA {
            get {
                return this.aUDIO_FECHAField;
            }
            set {
                this.aUDIO_FECHAField = value;
            }
        }
        
        /// <remarks/>
        public bool AUDIO_ESTADO {
            get {
                return this.aUDIO_ESTADOField;
            }
            set {
                this.aUDIO_ESTADOField = value;
            }
        }
        
        /// <remarks/>
        public ESCUCHAS[] ESCUCHAS {
            get {
                return this.eSCUCHASField;
            }
            set {
                this.eSCUCHASField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PAGO {
        
        private CLIENTE cLIENTEField;
        
        private int pAGO_IDField;
        
        private string cLI_IDField;
        
        private string pAGO_CODField;
        
        private string pAGO_TIPOField;
        
        private System.Nullable<decimal> pAGO_MONTOField;
        
        private System.Nullable<System.DateTime> pAGO_FECHAField;
        
        private string pAGO_PENDIENTEField;
        
        private System.Nullable<bool> pAGO_ESTADOField;
        
        /// <remarks/>
        public CLIENTE CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        public int PAGO_ID {
            get {
                return this.pAGO_IDField;
            }
            set {
                this.pAGO_IDField = value;
            }
        }
        
        /// <remarks/>
        public string CLI_ID {
            get {
                return this.cLI_IDField;
            }
            set {
                this.cLI_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PAGO_COD {
            get {
                return this.pAGO_CODField;
            }
            set {
                this.pAGO_CODField = value;
            }
        }
        
        /// <remarks/>
        public string PAGO_TIPO {
            get {
                return this.pAGO_TIPOField;
            }
            set {
                this.pAGO_TIPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PAGO_MONTO {
            get {
                return this.pAGO_MONTOField;
            }
            set {
                this.pAGO_MONTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PAGO_FECHA {
            get {
                return this.pAGO_FECHAField;
            }
            set {
                this.pAGO_FECHAField = value;
            }
        }
        
        /// <remarks/>
        public string PAGO_PENDIENTE {
            get {
                return this.pAGO_PENDIENTEField;
            }
            set {
                this.pAGO_PENDIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> PAGO_ESTADO {
            get {
                return this.pAGO_ESTADOField;
            }
            set {
                this.pAGO_ESTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mostrarServicioCompletedEventHandler(object sender, mostrarServicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mostrarServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mostrarServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servicio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servicio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MostrarPagosPALCompletedEventHandler(object sender, MostrarPagosPALCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostrarPagosPALCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostrarPagosPALCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MostrarPagosPAL Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MostrarPagosPAL)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mostrarPagosPALsCompletedEventHandler(object sender, mostrarPagosPALsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mostrarPagosPALsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mostrarPagosPALsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MostrarPagosPAL[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MostrarPagosPAL[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarEstadoCompletedEventHandler(object sender, ActualizarEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591